### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by l80** [Vorski-Imagineering/share#140]
Shell command log:

``` Shell
l80 at MacBook-Air-Andrey.local  /Volumes/svnnew/l80_ on master
$ mkdir share
l80 at MacBook-Air-Andrey.local  /Volumes/svnnew/l80_ on master
$ git clone git+ssh://git@github.com/ShareApp/share.git ./share/
Cloning into './share'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
remote: Counting objects: 1094, done.
remote: Compressing objects: 100% (493/493), done.
remote: Total 1094 (delta 526), reused 1094 (delta 526)
Receiving objects: 100% (1094/1094), 3.33 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (526/526), done.
Checking connectivity... done.
l80 at MacBook-Air-Andrey.local  /Volumes/svnnew/l80_ on master
$ cd share/
l80 at MacBook-Air-Andrey.local  /Volumes/svnnew/l80_/share on master
$ ls
Gruntfile.js LICENSE      Makefile     README.md    bower.json   cloudCode    docs         package.json settings     shareApp
l80 at MacBook-Air-Andrey.local  /Volumes/svnnew/l80_/share on master
$ npm install --dev
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/grunt-contrib-coffee
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-compass
npm http GET https://registry.npmjs.org/grunt-contrib-jshint
npm http GET https://registry.npmjs.org/grunt-contrib-cssmin
npm http GET https://registry.npmjs.org/grunt-contrib-connect
npm http GET https://registry.npmjs.org/grunt-contrib-clean
npm http GET https://registry.npmjs.org/grunt-contrib-htmlmin
npm http GET https://registry.npmjs.org/grunt-contrib-imagemin
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-usemin
npm http GET https://registry.npmjs.org/grunt-rev
npm http GET https://registry.npmjs.org/grunt-karma
npm http GET https://registry.npmjs.org/grunt-open
npm http GET https://registry.npmjs.org/grunt-concurrent
npm http GET https://registry.npmjs.org/matchdep
npm http GET https://registry.npmjs.org/grunt-ngmin
npm http GET https://registry.npmjs.org/grunt-ngdocs
npm http GET https://registry.npmjs.org/grunt-google-cdn
npm http GET https://registry.npmjs.org/connect-livereload

npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:483:26)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! cwd /Volumes/svnnew/l80_/share
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Volumes/svnnew/l80_/share/npm-debug.log
npm not ok
```

**Comment by vvorski** [comment]
@l80  have you tried this? http://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command

**Comment by l80** [comment]
l80_ at MacBook-Air-Andrey.local  /Volumes/svnnew/l80__/share on master
$ sudo npm cache clean -f
Password:
l80_ at MacBook-Air-Andrey.local  /Volumes/svnnew/l80__/share on master
$ sudo npm install -g n
npm http GET https://registry.npmjs.org/n

npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:483:26)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "n"
npm ERR! cwd /Volumes/svnnew/l80__/share
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Volumes/svnnew/l80__/share/npm-debug.log
npm not ok

**Comment by stefan8** [comment]
Why do you use so old nodejs?
You can try this one: npm conf set strict-ssl false
But wouldnt recommend this. Just upgrade nodejs and npm by homebrew or whatever u use on osx.
